- name: using facts
  hosts: all
  gather_facts: yes
  tasks:
    - debug: 
        msg: "{{ ansible_default_ipv4.address }}"
    - debug:
        msg: "{{ ansible_fqdn }}"
    - debug:
        msg: "{{ ansible_memory_mb }}"

